MODEL:
  META_ARCHITECTURE: "LanguageModel"
  LSTM:
    VOCAB_N: 12731
    HIDDEN: 1024
    DROPOUT: 0
LOSS_WEIGHTS:
  USE_TEXT_LOSS: True
  TEXT_LOSS: 1.0
DATASETS:
  TRAIN: ("refcocogoogle_train", "refcocogoogle_val")
  TEST: ("refcocogoogle_test",)
DATALOADER:
  SIZE_DIVISIBILITY: 32
SOLVER:
  BASE_LR: 0.02
  WEIGHT_DECAY: 0.0001
  STEPS: (60000, 80000)
  MAX_ITER: 10000
OUTPUT_DIR: output/LSTM_language_experiments/
